name: afri_shop
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0-rc
  flutter_local_notifications: ^1.4.4+4
  shared_preferences: ^0.5.3+4
  carousel_slider: ^1.4.1
  flutter_staggered_grid_view: ^0.3.0
  video_thumbnail: ^0.2.1
  image_picker: ^0.6.0+17
  multi_image_picker: ^4.7.11
  permission_handler: ^5.0.0+hotfix.8
  video_player: ^0.10.2+1
  pin_code_text_field: ^1.5.1
  bezier_chart: ^1.0.16
  path_provider: ^1.6.9
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  dio: ^3.0.9
  flutter_webview_plugin: ^0.3.11
  url_launcher: ^5.0.3
  firebase_messaging: ^6.0.16
  intl: ^0.16.1
  share: ^0.6.3+6
  mime: ^0.9.6+3
  html: ^0.14.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/afrishop_logo@3x.png
    - assets/home_banner.png
    - assets/loading_def.png
    - assets/boys.jpg
    - assets/home.png
    - assets/home_.png
    - assets/discover.png
    - assets/btnicon_more.png
    - assets/discover_.png
    - assets/add_photo.png
    - assets/take_a_photo.png
    - assets/cart.png
    - assets/coupons-dis.png
    - assets/new_logo.png
    - assets/order_detail.png
    - assets/unpaid.png
    - assets/purchased.png
    - assets/sending.png
    - assets/finished.png
    - assets/contact_us.png
    - assets/payment_icon.png
    - assets/mastercard.png
    - assets/verve.png
    - assets/visa.png
    - assets/jcb.png
    - assets/feedback.png
    - assets/faq.png
    - assets/dollar.png
    - assets/location.png
    - assets/success.png
    - assets/support.png
    - assets/camera.png
    - assets/share.png
    - assets/cart_.png
    - assets/account-order.png
    - assets/account_address.png
    - assets/account_coupons.png
    - assets/favorites-sel.png
    - assets/tabbar_support.png
    - assets/no_record.png
    - assets/arrived.png
    - assets/facebook.png
    - assets/google.png
    - assets/wallet.png
    - assets/flutterwave.png
    - assets/dpo.jpg
    - assets/empty.png
    - assets/coupon-empty.jpg
    - assets/arrow_down.png
    - assets/arrow_up.png
    - assets/favourite.png
    - assets/star.png
    - assets/home_delete.png
    - assets/hand.png
    - assets/back.png
    - assets/dot.png
    - assets/star_border.png
    - assets/pay.png
    - assets/insta.png
    - assets/account_edit.png
    - assets/personal_center.png
    - assets/search.png
    - assets/comments.png
    - assets/preview.jpg
    - assets/pay-failure.png
    - assets/sign_bg.png
    - assets/openeye.png
    - assets/search_v2.png
    - assets/forwarding.png
    - assets/horiz_more.png
    - assets/big_cart.png
    - assets/eye_closed.png
    - assets/account_user.png
    - assets/logo_circle.png
    - assets/logo_black.png
    - assets/log_bg.png
    - assets/about_logo.png
    - assets/small_like.png
    - assets/safety.png
    - assets/purchase.png
    - assets/img_fill.png
    - assets/search_app.png
    - assets/coupons-layer.png
    - assets/account_about.png
    - assets/account_log_out.png
    - assets/account_faq.png
    - assets/account_feedback.png
    - assets/account_ver.png
    - assets/account_share.png
    - assets/account.png
    - assets/account_.png
    - assets/withdraw.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Asimov
      fonts:
        - asset: fonts/AsimovNar.otf
    - family: DIN Alternate
      fonts:
        - asset: fonts/DIN-Alternate-Regular.otf
    - family: DIN Alternate Bold
      fonts:
        - asset: fonts/DIN-Alternate-Bold.ttf
    - family: FuturaBT-MediumItalic
      fonts:
        - asset: fonts/FuturaBT-MediumItalic.otf
    - family: SF UI Display
      fonts:
        - asset: fonts/SF-UI-Display-Regular.otf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
